### ISSUE TITLE
Compacting drawer does not "understand" copper nuggets

### ISSUE THREAD

**Issue by arisgoun** [EnigmaticaModpacks/Enigmatica9#247] opened 2023-02-28 18:42 UTC
### Modpack Version

1.4.2 Beta

### Describe your issue.

As in the title:
![2023-02-28_19 40 28](https://user-images.githubusercontent.com/70166657/221948697-99725d6e-854d-4dc1-81a6-dfaefaaea0f1.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment] 2023-02-28 19:01
Thank you for the report, we will investigate the issue.

**Comment by hezamu** [comment] 2023-04-07 10:41
This is because the nugget from Create is not compatible with the Minecraft copper ingot for some reason.

Workaround is to add the nugget as the first item into an empty compacting drawer, then the drawer will work as expected.

**Comment by Kanzaji** [comment] 2023-04-07 10:42
The issue is going to be fixed in next update with the release of #146

**Comment by hezamu** [comment] 2023-04-07 10:43
Ok, great. Just added the workaround here since the issue didn't have the tag.

**Closed** 2023-04-28 17:48 UTC
Labels: Bug, Status: Fixed In Next Release
