### ISSUE TITLE
[Mod suggestion] CC:tweaked

### ISSUE THREAD

**Issue by mick-2006** [EnigmaticaModpacks/Enigmatica9#69] opened 2022-10-12 06:42 UTC
### URL

https://www.curseforge.com/minecraft/mc-mods/cc-tweaked/files/4013870

### Why would you like the mod added?

Hi, so I noticed cc:tweaked wasn't included into Engimatica9? I, don't know if this was intentional or not but cc:tweaked in previous Engimatica9 packs was helpful for automation mainly in E6E, its mainly helpful for automating Pneumatic Craft Repressurized machines its simple lua code is handy for automating tasks that ae2 cannot do specifically Ars Nouveau, so in conclusion i recommend adding back CC:tweaked

**Comment by Kanzaji** [comment] 2022-10-12 06:48
Duplicate of #2
Unfortunetaly it's intentional ;-;

**Closed** 2022-10-12 07:05 UTC
Labels: Duplicate
