### ISSUE TITLE
Mekanism Flourite Clusters Bugged

### ISSUE THREAD

**Issue by benjamin-antupit** [EnigmaticaModpacks/Enigmatica9#816] opened 2023-12-24 21:41 UTC
### Modpack Version

1.16.1

### Describe your issue.

Using an RF Tools Builder with Quarry in the overworld, the items in the two attached screenshots are mined, but do not have any crafting recipies associated. I'd like to use Fluorite in the Mekanism Chemical Dissolution Chamber.
<img width="567" alt="Screenshot 2023-12-24 at 4 38 05 PM" src="https://github.com/EnigmaticaModpacks/Enigmatica9/assets/15172054/6a8f5494-83a3-4bf1-b3bc-3be9adfaf9bf">
<img width="625" alt="Screenshot 2023-12-24 at 4 38 00 PM" src="https://github.com/EnigmaticaModpacks/Enigmatica9/assets/15172054/c4d4c506-2593-4fd9-8e84-d84256aadfb0">

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

benjamin.antupit

**Comment by benjamin-antupit** [comment] 2023-12-25 06:20
I also just found budding Fluorite in the nether and breaking the fully-grown buds drops the same `Fluorite Cluster Shard` with missing texture as seen above. I'm not sure what the ideal resolution is, but I figure enabling this item and its crafting recipes would potentially work?

**Comment by Kanzaji** [comment] 2023-12-25 11:36
Thanks for the report!

I am unable to reproduce this issue on E9 Develop and E9 1.16.1 (Both Normal and Expert) >.>

Looking at other issues you have encountered (#817 #814) I have a suspision your instance might be corrupted... Mind sending over the `latest.log` from your instance for investigation what might have happened 😅? (After that I would recommend trying to reinstall the pack.)

**Comment by MuteTiefling** [comment] 2024-01-16 03:42
Closing these out as I cannot reproduce and they appear to be due to a bad install.

**Closed by MuteTiefling** 2024-01-16 03:42 UTC
Labels: Bug
