### ISSUE TITLE
Compacting Drawers do not recognize EE Copper Nuggets as nuggets of a Minecraft Copper Ingot

### ISSUE THREAD

**Issue by MaverickX7** [EnigmaticaModpacks/Enigmatica9#537] opened 2023-07-26 04:35 UTC
### Modpack Version

1.8.1

### Describe your issue.

Putting a Minecraft Copper Ingot in the Compacting Drawer shows Ingots and Blocks, but not Nuggets. Nuggets cannot be placed in. 
Putting Emendatus Enigmatica Copper Nuggets in a Compacting Drawer shows nuggets, ingots, and blocks, but you cannot place Copper Ingots or Blocks from Minecraft inside.
![image_2023-07-26_003452996](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/139928707/5a9365fc-0944-41e8-9712-167f17f24cba)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

maverick_x7

**Comment by NielsPilgaard** [comment] 2023-07-26 10:18
Thanks for the report.

I can't reproduce this part: 
> Putting Emendatus Enigmatica Copper Nuggets in a Compacting Drawer shows nuggets, ingots, and blocks, but you cannot place Copper Ingots or Blocks from Minecraft inside.

When I put nuggets in first, it works as expected, I can place Copper Ingots from Minecraft inside.

I don't think we're able to solve the issue though - @Buuz135, I don't see any way to configure Functional Storage, do we have any options here?

**Comment by MuteTiefling** [comment] 2023-07-26 11:45
I'm guessing here, but could the auto detection it's probably doing be thrown off by the conversion recipes? EE to minecraft

**Comment by theboo** [comment] 2023-07-26 11:48
If that's the case, I think the warnings on EE mats to be removed have been there long enough lol, time to yeet! If possible to yeet without breaking ee ofc(it really didn't like us removing something before but I forget what), if not then just recipe yeet!

**Comment by MuteTiefling** [comment] 2023-07-26 14:24
Well, removing the conversion scripts didn't fix it. Think we need buuz's input here on how it detects nuggets/ingots/blocks

**Comment by Kanzaji** [comment] 2023-08-26 09:44
I decided to spent few hours and read Buuz's code, and I found out how to Force FunctionalStorage to recognize the nugget :D
Fix is in the PR #666 !
Unfortunetaly I had to sacrifice tags in the nugget to ingot recipe, but I think a tiny smaller support for non-unified items is better than Compacting Drawers not giving nuggets 😄

**Closed** 2023-08-28 18:02 UTC
Labels: Bug, Status: Fixed In Next Release
