### ISSUE TITLE
bee dimenstion teleported me to overworld

### ISSUE THREAD

**Issue by mProjectsCode** [EnigmaticaModpacks/Enigmatica9#742] opened 2023-10-24 13:25 UTC
### Modpack Version

1.15.0 expert

### Describe your issue.

I went to the bee dimension, then exited it via digging up to y=255, then jumped and ended up in the overworld.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

lemons_dev

**Comment by mProjectsCode** [comment] 2023-10-24 13:31
additional context: I can repo the issue and I entered the bee dimension through an ars nouveau portal

**Comment by MuteTiefling** [comment] 2023-10-27 22:27
So far I'm unable to reproduce this. Some more information/context would likely be useful.

For my test, I teleported to the BumbleZone by ender pearling into a hive block. I then flew up through the roof and appeared right where my hive block was.

I then teleported back in with another pearl, bound a Stabilized Warp Scroll to the dimension, then flew up and out via the same hole. Again, I ended up back in front of my hive block in the Twilight Forest.

Next, I warped into the Bumblezone with the warp scroll and proceeded to fly up and out. Again, I returned back to the twilight forest. 

Finally, I broke my original hive and teleported back in with the warp scroll. I still appeared in front of the hive when I came back out.

How did you originally get to the bumblezone? Did you use a hive as intended? Has anything else unusual happened such as teleporting with commands?

**Comment by mProjectsCode** [comment] 2023-10-27 22:38
I never used an ender pearl on a hive. Another player set up the portal while I was offline. And we did not use any commands except spectator mode so that i could get back to the twilight forest.

**Comment by MuteTiefling** [comment] 2023-10-28 01:27
Alright thanks, that helps a lot. 

So for now, you can fix your character by going through the hive once to set the proper data on your player data. 

I'll work on fixing this on our end.

**Comment by MuteTiefling** [comment] 2023-10-28 01:52
Fix is two parts. We never defined a default exit dim for Bumblezone which allowed this to happen. That's now added.

That config option doesn't appear to work yet, however. This has been reported to TelepathicGrunt and will be fixed in the next BZ update.

**Comment by TelepathicGrunt** [comment] 2023-10-28 04:24
fixed in v7.0.25

**Comment by MuteTiefling** [comment] 2023-12-12 23:24
@TelepathicGrunt Does that mean no fix for 1.19.2?

**Comment by TelepathicGrunt** [comment] 2023-12-12 23:25
@MuteTiefling have you tried newest 1.29.2 bumblezone to see if issue still persist?

**Comment by TelepathicGrunt** [comment] 2023-12-12 23:26
![image](https://github.com/EnigmaticaModpacks/Enigmatica9/assets/40846040/2412e0bf-d15f-4fed-b084-389226eb4d8d)

**Comment by MuteTiefling** [comment] 2023-12-12 23:35
I haven't tested no. Was just going off of the version number. I'll check it soon

**Comment by MuteTiefling** [comment] 2023-12-13 14:13
@TelepathicGrunt Working great, thanks!

**Closed by MuteTiefling** 2023-12-13 14:13 UTC
Labels: Bug, Mod Issue, Status: Reported
