### ISSUE TITLE
Nature's Aura Infused Iron Recipes Disabled

### ISSUE THREAD

**Issue by benjamin-antupit** [EnigmaticaModpacks/Enigmatica9#817] opened 2023-12-24 22:14 UTC
### Modpack Version

1.16.1

### Describe your issue.

All crafting table recipes with Nature's Aura `Infused Iron` are disabled. Could these be added?

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

benjamin.antupit

**Comment by Kanzaji** [comment] 2023-12-25 11:25
Thanks for the report!

So... you shouldn't be able to obtain Infused Iron from Nature's Aura in the first place... All ingots are unified (and except vanilla onse) are replaced with EmendatusEnigmatica versions. Mind checking out recipes for that ingot, those should be tagged and the NA's Infused Iron should still work for them 😄.

Also do you remember how did you got the NA's ingot 👀?

**Comment by MuteTiefling** [comment] 2024-01-16 03:42
Closing these out as I cannot reproduce and they appear to be due to a bad install.

**Closed by MuteTiefling** 2024-01-16 03:42 UTC
Labels: Bug
