### ISSUE TITLE
Random Crashing

### ISSUE THREAD

**Issue by Joprebond** [EnigmaticaModpacks/Enigmatica9#355] opened 2023-05-21 01:10 UTC
### Modpack Version

1.6.0

### Describe your issue.

The Came will randomly lockup and then crash from time to time.

### Crash Report

https://gist.github.com/Joprebond/a2668d5445a9f503848ff44d9a33c78c

### Latest Log

https://gist.github.com/Joprebond/ba0ee25d3bb8d71e54858312ec2b145b

### Have you modified the modpack?

Yes

### User Modifications

I added the mods below to the pack.

ContentCreatorIntegration-1.19.2-Forge-1.10.3
ContentCreatorIntegration-1.19.2-Forge-1.10.3-api

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

JoprebondOdin#5307

**Comment by theboo** [comment] 2023-05-21 03:22
Duplicate of #352, should be fixed next update... There's instructions in that issue on how to fix it on your server or single player world.. if on server change only needs to be on server

**Closed** 2023-05-21 03:25 UTC
Labels: Bug, Duplicate
