### ISSUE TITLE
[Mod Suggestion] Tetra

### ISSUE THREAD

**Issue by TonySchoborg** [EnigmaticaModpacks/Enigmatica9#223] opened 2023-02-04 23:13 UTC
### URL

https://www.curseforge.com/minecraft/mc-mods/tetra/files?sort=filelength

### Why would you like the mod added?

Tetra looks like it just updated to 1.19.2. It has become one of our favorite mods.

**Comment by Kanzaji** [comment] 2023-02-04 23:15
Duplicate of #221

**Closed** 2023-02-04 23:59 UTC
Labels: Suggestion
